// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzPQ2nSlql343SodgY_qUicC1jxkuVv4',
    appId: '1:610317322829:web:4a9518213ee1c0c2746a04',
    messagingSenderId: '610317322829',
    projectId: 'handyman-service-app-76497',
    authDomain: 'handyman-service-app-76497.firebaseapp.com',
    storageBucket: 'handyman-service-app-76497.firebasestorage.app',
    measurementId: 'G-QPHCJJCQWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-tmkJjwr0303VH6aE2FR7PDiOiu9mCsc',
    appId: '1:610317322829:android:bf7eff416b735e8a746a04',
    messagingSenderId: '610317322829',
    projectId: 'handyman-service-app-76497',
    storageBucket: 'handyman-service-app-76497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK8Qlxv6t43J3AHlskSyGaJQZSJ0Go-yk',
    appId: '1:610317322829:ios:6b222b53bf88a18c746a04',
    messagingSenderId: '610317322829',
    projectId: 'handyman-service-app-76497',
    storageBucket: 'handyman-service-app-76497.firebasestorage.app',
    iosBundleId: 'com.example.flutterHandymanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK8Qlxv6t43J3AHlskSyGaJQZSJ0Go-yk',
    appId: '1:610317322829:ios:6b222b53bf88a18c746a04',
    messagingSenderId: '610317322829',
    projectId: 'handyman-service-app-76497',
    storageBucket: 'handyman-service-app-76497.firebasestorage.app',
    iosBundleId: 'com.example.flutterHandymanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTzPQ2nSlql343SodgY_qUicC1jxkuVv4',
    appId: '1:610317322829:web:26c72e9560083b68746a04',
    messagingSenderId: '610317322829',
    projectId: 'handyman-service-app-76497',
    authDomain: 'handyman-service-app-76497.firebaseapp.com',
    storageBucket: 'handyman-service-app-76497.firebasestorage.app',
    measurementId: 'G-3S5R8Q26WE',
  );
}
