name: flutter_handyman_app
description: "A new Flutter project."

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0  # Update to the latest compatible version
  firebase_auth: ^6.0.0  # Update to the latest compatible version
  cloud_firestore: ^6.0.0  # Update to the latest compatible version

  cupertino_icons: ^1.0.8  # Cupertino icons for iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0  # Lints for Flutter project

flutter:
  assets:
    - assets/images/  # Your images directory
  uses-material-design: true  # Enable material design icons
